[project]
name = "token-vesting"
requirements = []
costs_version = 1

[contracts.token-vesting]
path = "contracts/token-vesting.clar"
depends_on = ["sip-010-trait"]

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
depends_on = []

[contracts.xyz-token]
path = "tests/contracts/xyz-token.clar"
depends_on = ["sip-010-trait"]
